name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  depcheck-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Dependency audit
        uses: tj-actions/depcheck@v9
        with:
          ignores: >
            eslint,prettier,
            pg,autoprefixer,postcss,esbuild,
            @assets/*

      - name: Build project
        run: npm run build
