name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  depcheck-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Dependency audit
        uses: tj-actions/depcheck@v9
        with:
          ignores: >
             eslint,prettier,
             pg,
             autoprefixer,postcss,esbuild,
             @assets/*                # alias-based images
          
      - run: npm run build
